# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Atualizar_tabelas_qgis
                                 A QGIS plugin
 Atualizer é um plugin criado com o intuito de atualizar os dados da tabela de atributos de uma camada usando os dados importados de um tabela do excel.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-10
        copyright            : (C) 2025 by Guilherme Guedes Barbosa  -  Jean Carlos Araújo
        email                : guedesguilherme01912@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Atualizar_tabelas_qgis class from file Atualizar_tabelas_qgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .atualizer_plugin import Atualizar_tabelas_qgis
    return Atualizar_tabelas_qgis(iface)
